apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-w4fd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-w4fd
    app.kubernetes.io/part-of: tkrw-pr712-0075-0069-app
  name: devfile-sample-w4fd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-w4fd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-w4fd
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0069-tenant/tkrw-pr712-0075-0069-app/devfile-sample-w4fd@sha256:a7a9c44ee1001114bcb7ad518fcebcd0e5be78dcdd1d14c1ec630bd18270f574
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
